import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import notificationRoutes from '../modules/notification/notification.routes';
import profileRoutes from '../modules/profile/profile.routes';
import termsRoutes from '../modules/terms/terms.routes';
import privacyRoutes from '../modules/privacy/privacy.routes';
import faqRoutes from '../modules/faq/faq.routes';
import aboutRoutes from '../modules/about/about.routes';
import adminRoutes from '../modules/admin/admin.routes';
import locationRoutes from '../modules/location/location.routes';
import chatRoutes from '../modules/chat/chat.routes';
import supportRoutes from '../modules/support/support.routes';
import subscriptionRoutes from '../modules/subscriptions/subscription.routes';
import onboardingRoutes from '../modules/onboarding/onboarding.routes';
import assessmentRoutes from '../modules/assessment/assessment.routes';

import paymentRoutes from '../modules/payment/payment.routes';
import categoryRoutes from '../modules/category/category.routes';
import journeyRoutes from '../modules/journey/journey.routes';
import bilateralRoutes from '../modules/bilateral/bilateral.routes';
import progressRoutes from '../modules/progress/progress.routes';
import sessionProgressRoutes from '../modules/progress/sessionProgress.routes';
import watchTimeRoutes from '../modules/progress/watchTime.routes';
import uploadRoutes from '../modules/upload/upload.routes';
import calmPlaceRoutes from '../modules/calm-place/calmPlace.routes';
import exposureRoutes from '../modules/exposure/exposure.routes';
import cbtFormulationRoutes from '../modules/cbt-formulation/cbtFormulation.routes';
import emdrSessionRoutes from '../modules/emdr-session/emdrSession.routes';
import myTestsRoutes from '../modules/my-tests/myTests.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/notifications', notificationRoutes);
router.use('/profile', profileRoutes);
router.use('/terms', termsRoutes);
router.use('/privacy', privacyRoutes);
router.use('/faq', faqRoutes);
router.use('/about', aboutRoutes);
router.use('/admin', adminRoutes);
router.use('/location', locationRoutes);
router.use('/chat', chatRoutes);
router.use('/support', supportRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/onboarding', onboardingRoutes);
router.use('/assessment', assessmentRoutes);
router.use('/payment', paymentRoutes);
router.use('/', categoryRoutes);
router.use('/journeys', journeyRoutes);
router.use('/bilateral', bilateralRoutes);
router.use('/progress', progressRoutes);
router.use('/session-progress', sessionProgressRoutes);
router.use('/watch-time', watchTimeRoutes);
router.use('/upload', uploadRoutes);
router.use('/calm-place', calmPlaceRoutes);
router.use('/exposure', exposureRoutes);
router.use('/cbt-formulation', cbtFormulationRoutes);
router.use('/emdr-session', emdrSessionRoutes);
router.use('/my-tests', myTestsRoutes);

export default router;
